[package]
name = "late"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

# flatpak suggest using XDG_CONFIG_HOME. if not in flatpak,
# this should default to user's home. to have both available,
# the directories-rs crate can be used
# https://codeberg.org/dirs/directories-rs
directories = "5.0"
